### PR TITLE
Initial unity 5.0 support

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
I tested it on creativerse.

Problems:
1) in some cases I cannot determine externals block position
2) AudioClipExtractor doesnt with resources that are contained in separate binary file, linked through "m_Resource" field.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Found an issue: https://github.com/ata4/disunity/issues/140

**Comment by ivanpopelyshev** [comment]
One more: https://github.com/ata4/disunity/issues/135

**Comment by ivanpopelyshev** [comment]
And more: https://github.com/ata4/disunity/issues/130

**Comment by ata4** [comment]
The title confused me a bit at first, since there's already some Unity 5 support in the code, but it looks like you fixed some issues in the extraction module. I'll merge it, thanks!

**Comment by wartoghex** [comment]
Are you gonna add the 5.1.3f1 type to dat?

**Pull request merged**
